<?php

return [
    'admins' => 'Manage admins',
    'categories' => 'Manage Categories',
    'create_categories' => 'Create Categories',
    'brands' => 'Manage Brands',
    'coupons' => 'Manage coupons',
    'products' => 'Manage Products',
    'orders' => 'Manage Orders',
    'users' => 'Manage Users',
    'roles' => 'Manage Roles',
    'settings' => 'Manage Settings',
    'reports' => 'Manage Reports',
    'dashboard' => 'Manage Dashboard',
    'profile' => 'Manage Profile',
    'home' => 'Manage Home',
    'contact' => 'Manage Contact',
    'about' => 'Manage About',
    'blog' => 'Manage Blog',
    'newsLetters' => 'Manage News Letters',
    'sliders' => 'Manage Sliders',
    'pages' => 'Manage Pages',
    'faqs' => 'Manage Faqs',
    'comments' => 'Manage Comments',
    'socials' => 'Manage Socials',
    'menus' => 'Manage Menus',
    'global_shipping' => 'Shipping Management',
    'attributes' => 'Manage Attributes',
];
